parameters:
- name: environmentName
  type: string
  default: 'dev'
- name: templateFileName
  type: string
  default: 'main'
- name: templateDirectory
  type: string
  default: 'infrastructure'
- name: serviceName
  type: string
  default: 'SamleApp'
- name: regionAbrv
  type: string
  default: 'cus'
- name: paramExt
  type: string
  default: '.json'
jobs:
- job: whatif_${{ parameters.serviceName }}_${{ parameters.environmentName }}_${{ parameters.regionAbrv }}
  variables: 
  - template: ../variables/azure_${{ parameters.environmentName }}_variables.yml
  steps:
    - template: ../tasks/azcli_sub_deploy_task.yml
      parameters:
          azureSubscriptionName: ${{ variables.azureServiceConnectionName}}
          templateFileName: ${{ parameters.templateDirectory }}/${{ parameters.templateFileName }}.bicep
          parametersFileName: '${{ parameters.templateDirectory }}/parameters/${{ parameters.environmentName }}.${{ parameters.regionAbrv }}.parameters${{ parameters.paramExt }}'
          command: 'validate'
    - template: ../tasks/azcli_sub_deploy_task.yml
      parameters:
          azureSubscriptionName: ${{ variables.azureServiceConnectionName}}
          templateFileName: ${{ parameters.templateDirectory }}/${{ parameters.templateFileName }}.bicep
          parametersFileName: '${{ parameters.templateDirectory }}/parameters/${{ parameters.environmentName }}.${{ parameters.regionAbrv }}.parameters${{ parameters.paramExt }}'
          command: 'what-if'
          additionalArguments: '--out yamlc'
