parameters:
- name: artifactName
  type: string
  default: ''
- name: serviceName
  type: string
  default: ''
jobs:
  - job: validate_${{ parameters.serviceName}}
    displayName: 'Validate ${{ parameters.serviceName }} Bundle'
    steps:
    - template: ../tasks/cmd_execute_task.yml
      parameters:
        scriptContent: 'curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh'
        displayName: 'Install Databricks CLI v 2'
    - template: ../tasks/azcli_inline_script_task.yml
      parameters:
        azureSubscriptionName: 'adb-sc'
        inlineScript: 'cd ${{ parameters.artifactName }}
          databricks bundle validate'



   
