parameters:
- name: artifactName
  type: string
  default: ''
- name: serviceName
  type: string
  default: ''
jobs:
  - job: validate_${{ parameters.serviceName}}
    displayName: 'Validate ${{ parameters.serviceName }} Bundle'
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
      displayName: 'Install Databricks CLI v 2'
    - task: AzureCLI@2
      displayName: 'Validate Vundle'
      inputs:
        azureSubscription: 'adb-sc'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd ${{ parameters.artifactName }}
          databricks bundle validate
