parameters:
- name: serviceName
  type: string
  default: ''
- name: dockerFile
  type: string
  default: '**/Dockerfile'
- name: tags
  type: string
  default: 'latest'
- name: buildContext
  type: string
  default: '**'
- name: arguments
  type: string
  default: ''
- name: environmentName
  type: string
- name: appSettingsPath
  type: string
  default: ''
- name: appPath
  type: string
  default: ''
jobs:
- job: 'docker_${{ parameters.serviceName }}_${{ parameters.environmentName }}_build'
  steps:
  - template: ../tasks/ado_file_transform_task.yml
    parameters:
      folderPath: ${{ parameters.appSettingsPath }}
      jsonTargetFiles: '${{ parameters.appSettingsPath }}/${{ parameters.environmentName }}.json'
  - template: ../tasks/docker_build_task.yml
    parameters:
      dockerFile: ${{ parameters.dockerFile }}
      tags: ${{ parameters.tags }}
      buildContext: ${{ parameters.buildContext }}
      arguments: ${{ parameters.arguments }}
      serviceName: ${{ parameters.serviceName }}
      
