parameters:
- name: environmentObjects
  type: object
  default:
      environmentName: 'dev'
      regionAbrvs: ['cus']
- name: environmentName
  type: string
  default: ''
- name: templateParametersFile
  type: string
  default: 'parameters'
- name: serviceName
  type: string
  default: ''
- name: linkedTemplates
  type: boolean
  default: false

stages:
  - ${{ each environmentObject in parameters.environmentObjects }} :
    - ${{ each regionAbrv in environmentObject.regionAbrvs }} :
        - stage: '${{ parameters.serviceName }}_${{ environmentObject.environmentName}}_${{regionAbrv}}_adf_deploy'
          variables:
            ${{ if eq(parameters.linkedTemplates, false)}} :
              templateFile: 'ARMTemplateForFactory.json'
            ${{ else }} :
              templateFile: 'linkedTemplates/ArmTemplate_master.json'
          jobs:
          ${{ if eq(parameters.linkedTemplates, false)}} :
            - template: ../jobs/adf_deploy_env_job.yml
              parameters:
                environmentName: ${{ environmentObject.environmentName }}
                templateFile: $(templateFile)
                templateParametersFile: ${{ parameters.templateParametersFile }}
                serviceName: ${{ parameters.serviceName}}
                regionAbrv: ${{ regionAbrv }}
          ${{ else }} :
            - template: ../jobs/adf_linked_template_deploy_env_job.yml
              parameters:
                environmentName: ${{ environmentObject.environmentName }}
                templateFile: $(templateFile)
                templateParametersFile: ${{ parameters.templateParametersFile }}
                serviceName: ${{ parameters.serviceName}}
                regionAbrv: ${{ regionAbrv }}
            
