parameters:
- name: environmentObjects
  type: object
  default:
    - environmentName: 'dev'
      regionAbrvs: ['cus']
- name: templateFileName
  type: string
  default: 'main'
- name: templateDirectory
  type: string 
  default: 'infrastructure'
- name: serviceName
  type: string
- name: deploymentScope
  type: string
  default: 'subscription'
stages:
- stage: '${{ parameters.serviceName }}_build'
  jobs:
  - template: ../jobs/ado_publish_job.yml
    parameters:
      targetPath: ${{ parameters.templateDirectory }}
      artifactname: ${{ parameters.templateDirectory }}
  - ${{ each environmentObject in parameters.environmentObjects }} :
    - ${{ each regionAbrv in environmentObject.regionAbrvs }} :
      - ${{ if eq(parameters.deploymentScope, 'subscription')}} :
        - template: ../jobs/bicep_whatif_env_job.yml
          parameters:
            environmentName: ${{ environmentObject.environmentName }}
            templateFileName: ${{ parameters.templateFileName }}
            templateDirectory: ${{ parameters.templateDirectory }}
            serviceName: ${{ parameters.serviceName }}
            regionAbrv: ${{ regionAbrv }}
      - ${{ elseif eq(parameters.deploymentScope, 'resourceGroup')}} : 
        - template: ../jobs/bicep_whatif_rg_env_job.yml
          parameters:
            environmentName: ${{ environmentObject.environmentName }}
            templateFileName: ${{ parameters.templateFileName }}
            templateDirectory: ${{ parameters.templateDirectory }}
            serviceName: ${{ parameters.serviceName }}
            regionAbrv: ${{ regionAbrv }}

    
