parameters:
- name: artifactName
  type: string
  default: ''
- name: serviceName
  type: string
  default: ''

stages:
- stage: ${{ parameters.serviceName }}_validate_deploy_bundles
  displayName: 'Validate and Publish ${{ parameters.serviceName }}
  jobs:
  - template: ../jobs/publish_pipeline_artifact_job.yml
    parameters:
      artifactName: ${{ parameters.artifactName }}
      pathToArtifact: '$(Pipeline.Workspace)/s/${{ parameters.artifactName }}'
  - template: ../jobs/dab_validate_job.yml
    parameters:
      artifactName: ${{ parameters.artifactName }}
