parameters:
- name: artifactName
  type: string
  default: ''
- name: serviceName
  type: string
  default: ''

stages:
- stage: ${{ parameters.serviceName }}_validate_deploy_bundles
  displayName: 'Validate and Publish ${{ parameters.serviceName }}'
  jobs:
  - template: ../jobs/ado_publish_job.yml
    parameters:
      artifactName: ${{ parameters.artifactName }}
      targetPath: '$(Pipeline.Workspace)/s/${{ parameters.artifactName }}'
  - template: ../jobs/dab_validate_job.yml
    parameters:
      artifactName: ${{ parameters.artifactName }}
