stages:
- stage: stg_validate_deploy_bundles
  displayName: 'validate_deploy_bundles'
  variables:
    - template: ../variables/global.yml
  jobs:
  - template: ../jobs/publish_pipeline_artifact_job.yml
    parameters:
      artifactName: ${{ variables.artifactName }}
      pathToArtifact: ${{ variables.bundleArtifactLocation }}
  - template: ../jobs/dab_validate_job.yml
    parameters:
      artifactName: ${{ variables.artifactName }}
